In [1]:
import numpy as np


In [2]:
def get_chess(a):
    ar_chess = np.zeros([a,a])
    ar_chess[0:a:2, 1:a:2] = 1
    ar_chess[1:a:2, 0:a:2] = 1
    return ar_chess


In [4]:
print(get_chess(1),"\n")

print(get_chess(8),"\n")

print(get_chess(4))


[[0.]] 

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]] 

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
